name: flutter_api_display
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  
  # Logger -- Logging
  logger: ^2.5.0

  # Intl -- Internationalization
  intl: ^0.19.0

  # Provider -- State Management
  provider: ^6.1.2

  # Result
  multiple_result: ^5.1.0

  # Lottie -- Animation
  lottie: ^3.3.1

  # Http -- Network
  http: ^1.3.0

  # Equatable
  equatable: ^2.0.5

  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.8


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  # Assets
  assets:
    - assets/animations/
